import psycopg2
from pgvector.psycopg2 import register_vector
import logging
from pathlib import Path
import yaml
import json

logger = logging.getLogger(__name__)

# Load config
CONFIG_PATH = Path(__file__).parent / "config.yaml"
if CONFIG_PATH.exists():
    with open(CONFIG_PATH, "r") as f:
        config = yaml.safe_load(f)
        pg_cfg = config.get("postgres", {})
else:
    pg_cfg = {}

NEON_CONNECTION_STRING = pg_cfg.get("connection_string", "YOUR_NEON_POSTGRES_CONNECTION_STRING")
PG_TABLE = pg_cfg.get("table", "file_embeddings")

def get_connection():
    """Establish a connection to the PostgreSQL database and register pgvector."""
    conn = psycopg2.connect(NEON_CONNECTION_STRING)
    # Register the vector type with psycopg2
    register_vector(conn)
    return conn

def init_db():
    """Initializes the Neon database by creating the pgvector extension and the required table."""
    conn = None
    try:
        # Connect raw first so we can create the extension without register_vector erroring
        conn = psycopg2.connect(NEON_CONNECTION_STRING)
        with conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        conn.commit()
        
        # Now register vector capabilities mapping
        register_vector(conn)
        
        with conn.cursor() as cur:
            create_table_query = f"""
                CREATE TABLE IF NOT EXISTS {PG_TABLE} (
                    id SERIAL PRIMARY KEY,
                    s3_key TEXT,
                    filename TEXT,
                    user_id BIGINT,
                    embedding VECTOR(384),
                    metadata JSONB
                );
            """
            cur.execute(create_table_query)
        conn.commit()
        logger.info(f"Database initialized: extension created and table '{PG_TABLE}' is ready.")
    except Exception as e:
        if conn:
            conn.rollback()
        logger.exception("Failed to initialize database.")
        raise
    finally:
        if conn:
            conn.close()

def insert_record(s3_key: str, filename: str, user_id: int, embedding: list[float], metadata: dict) -> None:
    """Insert a file record with its embedding into the PostgreSQL database.

    Args:
        s3_key: AWS S3 storage key/path.
        filename: Original file name.
        user_id: Telegram user ID.
        embedding: Vector embedding generated by HuggingFace.
        metadata: Additional JSON metadata (e.g., file size).
    """
    conn = None
    try:
        conn = get_connection()
        with conn.cursor() as cur:
            insert_query = f"""
                INSERT INTO {PG_TABLE} (s3_key, filename, user_id, embedding, metadata)
                VALUES (%s, %s, %s, %s, %s)
            """
            cur.execute(insert_query, (s3_key, filename, user_id, embedding, json.dumps(metadata)))
        conn.commit()
        logger.info(f"Inserted record for file {filename} into database.")
    except Exception as e:
        if conn:
            conn.rollback()
        logger.exception("Failed to insert record into database")
        raise
    finally:
        if conn:
            conn.close()

# If running this file directly, it will initialize the table on your Neon DB
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    init_db()
